---
- hosts: test
  gather_facts: no
  connection: local

###DNS
  vars:
    dns_servers:
      - ip name-server 10.128.2.60
      - ip name-server 10.128.2.61
    
    aaa_configs:
      - aaa new-model
      - aaa authentication login default group tacacs+ local
      - aaa authentication enable default group tacacs+ enable
      - aaa authorization config-commands
      - aaa authorization exec default group tacacs+ local
      - aaa accounting exec default start-stop group tacacs+
      - aaa accounting network default start-stop group tacacs+
      - aaa accounting connection default start-stop group tacacs+
      - aaa accounting system default start-stop group tacacs+
      - aaa session-id common

    names:
      - no_tacacs+


  tasks:

  - name: get the current name-server configs
    ios_command:
      commands:
        - "show running-config full | include ip name-server"
    register: get_config

  - debug: var=get_config.stdout_lines

  - name: set name-server commands
    with_items: "{{ dns_servers }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_dns

  - name: remove name-server commands
    when: "(get_config.stdout_lines[0] != '') and (item not in dns_servers)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_dns
    ios_config:
      lines:
        - "no {{ item }}"

###ACL
  - name: CHECK ACLS
    ios_command:
      commands:
        - show ip access-list
    register: beforeacl

  - debug: var=beforeacl.stdout_lines


  - name: CREATE ENVIGO ACL
    ios_config:
      commands:
        - 10 permit 10.128.0.0 0.0.255.255
      parents: ['ip access-list standard 16']
      before: ['no ip access-list standard 16']
      match: exact

    register: newacl

  - debug: var=newacl.stdout_lines

  - name: CHECK ACLS
    ios_command:
      commands:
        - show ip access-list
    register: afteracl

  - debug: var=afteracl.stdout_lines

###USERS
  - name: remove all users
    ios_user:
      purge: yes
    register: remove

  - debug: var=remove

  - name: create a new user
    ios_user:
      name: no_tacacs+
      configured_password: password.D15ast5r
      state: present
    register: create

  - debug: var=create
  
  - name: users to privilege level
    ios_user:
      name: no_tacacs+
      privilege: 15
      state: present
    register: priv
  - debug: var=priv

###DISABLE HTTPS
  - name: run enable level commands
    ios_config:
      commands:
        - no ip http server
        - no ip http secure-server
  - debug: msg="HTTP and HTTPS have been disabled"

###MOTD
  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "{{ lookup('file', '/etc/ansible/banner.cfg') }}"
      state: present

###AAA
  - name: get the current aaa configs
    ios_command:
      commands:
        - "show running-config full | include aaa"
    register: get_config
  - debug: var=get_config.stdout_lines

  - name: set aaa configs
    with_items: "{{ aaa_configs }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_aaa

  - name: remove aaa configs
    when: "(get_config.stdout_lines[0] != '') and (item not in aaa_configs)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_aaa
    ios_config:
      lines:
        - "no {{ item }}"

