---
- hosts: test
  gather_facts: no
  connection: local


  vars:
  
    dns_servers:
      - ip name-server 10.128.2.60
      - ip name-server 10.128.2.61
      
      

  tasks:
  
  - name: get the current name-server configs
    ios_command:
      commands:
        - "show running-config full | include ip name-server"
    register: get_config

  - debug: var=get_config.stdout_lines

  - name: set name-server commands
    with_items: "{{ dns_servers }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_dns

  - name: remove name-server commands
    when: "(get_config.stdout_lines[0] != '') and (item not in dns_servers)"
    with_items: "{{ get_config.stdout_lines[0] }}"
    register: remove_dns
    ios_config:
      lines:
        - "no {{ item }}"
